language: node_js
node_js:
  - "12"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^6"

install:
  - make deps

script:
  - make check

notifications:
  slack:
    secure: BXw3zt45l8M4Uu0rzyu4DhEza3PcXEw4eMrd+G9KLYFw039/XLPAhPOhcTrShRp8RR2e85NaTw5hJjl7chSpah+PvM9oLPV/yuwf6Wo9BZtSh1eFd+GWOWYyWlIALjUyDRQbqrrGM70aIky1gCGkb+93pJtJfyYWBW3TMWngYDQ=
