on:
  pull_request:
    types: [opened, closed]

name: Slack Notification
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: https://github.com/UNC_Libraries/Carolina-Digital-Repository/pull/${{ github.event.pull_request.number }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}